Make things more flexible
gfredericks/lein-all-my-files-should-end-with-exactly-one-newline-character pull request #2
Opened 2018-07-05 17:34 UTC by vemv

* Extract the core functionality to a standalone namespace, as we did in https://github.com/gfredericks/how-to-ns/pull/7
* Implement funcionality (programmatic + lein-invokable) to check/ensure file endings with _no_ newline ending. I don't encourage that style, but some people do use it and lein-all-my-files-should-end-with-exactly-one-newline-character would make our lives easier.

Cheers - Victor

2018-07-09 11:46 UTC, gfredericks requested changes
Looks good, just one change and I'll release it.

Thanks!

2018-07-09 11:46 UTC, gfredericks commented on src/gfredericks/all_my_files_should_end_with_exactly_one_newline_character.clj
> +(ns gfredericks.all-my-files-should-end-with-exactly-one-newline-character
`com.gfredericks` please

2018-07-09 11:53 UTC, vemv commented
Thanks for reviewing!

Done

2018-07-09 11:57 UTC, merged

2018-07-09 12:00 UTC, gfredericks commented
Released as `0.1.1`.

2020-02-19 21:01 UTC, vemv commented
I thought I'd let you know that I've wrapped this library + how-to-ns in the https://github.com/nedap/formatting-stack project.

It's a pretty nifty way to run these pieces of code without cold-starts :)

2020-02-19 21:14 UTC, gfredericks commented
Cool! If you'd like to add a pointer to this project's readme, feel free to make a PR.